[project]
name = 'stackycoin'
description = 'stackycoin del bueno'
authors = []
telemetry = true
cache_dir = './.cache'

[[project.requirements]]
contract_id = 'SP1AJVMEGSMD6QCSZ1669Z5G90GEHVK2MEM7J0AHH.stackycoin'

[contracts.stackycoin]
path = 'contracts/stackycoin.clar'
clarity_version = 4
epoch = "latest"

[contracts.defi]
path = 'contracts/extern/defi.clar'
clarity_version = 4
epoch = "latest"

